project_id = "odrtrdnjoppdgtaxngmh"

[functions.send-welcome-email]
verify_jwt = false

[functions.reset-employee-password]
verify_jwt = true

[functions.create-employee]
verify_jwt = true

[functions.check-eod-submission]
verify_jwt = false

[functions.sync-birthdays-to-calendar]
verify_jwt = false

[functions.send-shoutout-notification]
verify_jwt = true

[functions.send-feedback-notification]
verify_jwt = true

[functions.delete-employee]
verify_jwt = true

[functions.escalate-memos]
verify_jwt = false

[functions.assign-secret-santa]
verify_jwt = true

[functions.sync-reminders-to-calendar]
verify_jwt = false

[functions.generate-evaluation-summary]
verify_jwt = true
