project_id = "odrtrdnjoppdgtaxngmh"

[functions.send-welcome-email]
verify_jwt = false

[functions.reset-employee-password]
verify_jwt = true

[functions.create-employee]
verify_jwt = true

[functions.check-eod-submission]
verify_jwt = false

[functions.sync-birthdays-to-calendar]
verify_jwt = false
